trigger:
  - master

jobs:
  - job: 'Frontend'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: NodeTool@0
        inputs:
          versionSpec: '14'
    - script: npm install
      workingDirectory: components/frontend
    - script: npm run test:unit
      workingDirectory: components/frontend
    - script: npm run build
      workingDirectory: components/frontend
  - job: 'Backend'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: pip install -r requirements
      workingDirectory: components/api
    - script: pytest
      workingDirectory: components/api
  - job: 'Docker'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: dockerRegistryLoccitaneServiceConnection
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: password-checker
        tags: |
          latest



